[package]
name = "laffy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0.7"
taffy = "0.3.18"
tokio = { version = "1.35.0", features = ["full"] }
